'use client';

import { useState, type ReactNode } from 'react';
import Link from 'next/link';
import { usePathname, useRouter } from 'next/navigation';
import { BarChart3, Bell, ClipboardList, ExternalLink, KeyRound, LayoutDashboard, LogOut, Menu, PanelLeftClose, Settings, Users } from 'lucide-react';
import { projectMajors, projects as seedProjects, results as seedResults } from '../data/data';
import { Logo, cx } from './ui';

export function AdminShell({ children, title }: { children: ReactNode; title: string }) {
  const pathname = usePathname(); const router = useRouter(); const [drawer, setDrawer] = useState(false); const links = [{ href:'/admin', label:'Overview', icon:LayoutDashboard },{ href:'/admin/codes', label:'Codes', icon:KeyRound },{ href:'/admin/users', label:'Users', icon:Users },{ href:'/admin/projects', label:'Projects', icon:ClipboardList },{ href:'/admin/results', label:'Results', icon:BarChart3 },{ href:'/admin/settings', label:'Settings', icon:Settings }];
  return <div className="min-h-[100dvh] bg-background"><aside className={cx('fixed inset-y-0 left-0 z-30 w-64 border-r border-[#25374a] bg-[#0b121e] p-5 text-white transition-transform lg:translate-x-0', drawer ? 'translate-x-0' : '-translate-x-full')}><div className="flex items-center justify-between"><Logo inverse /><button onClick={() => setDrawer(false)} className="lg:hidden" aria-label="Close menu" data-testid="button-close-admin-menu"><PanelLeftClose size={18} /></button></div><div className="mt-12 space-y-1">{links.map(({ href, label, icon: Icon }) => <Link key={href} href={href} onClick={() => setDrawer(false)} className={cx('flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-semibold transition', pathname === href ? 'bg-primary/15 text-primary shadow-[inset_3px_0_0_hsl(188_100%_62%)]' : 'text-[#9cabb9] hover:bg-[#172536] hover:text-white')} data-testid={`link-admin-${label.toLowerCase()}`}><Icon size={18} />{label}</Link>)}</div><div className="absolute bottom-5 left-5 right-5 space-y-1 border-t border-white/10 pt-4"><Link href="/projects" className="flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-semibold text-[#9cabb9] hover:bg-[#172536] hover:text-white" data-testid="link-back-to-voting"><ExternalLink size={17} />Back to voting site</Link><button onClick={() => router.push('/')} className="flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-sm font-semibold text-[#9cabb9] hover:bg-[#172536] hover:text-white" data-testid="button-admin-sign-out"><LogOut size={17} />Sign out</button></div></aside>{drawer && <button className="fixed inset-0 z-20 bg-[#020711]/70 lg:hidden" onClick={() => setDrawer(false)} aria-label="Close navigation overlay" data-testid="button-overlay-close" />}<div className="lg:pl-64"><header className="sticky top-0 z-10 flex h-16 items-center justify-between border-b border-border bg-background/90 px-4 backdrop-blur sm:px-8"><div className="flex items-center gap-3"><button onClick={() => setDrawer(true)} className="grid h-10 w-10 place-items-center rounded-xl bg-card lg:hidden" aria-label="Open menu" data-testid="button-open-admin-menu"><Menu size={19} /></button><div><p className="text-xs font-semibold uppercase tracking-[.14em] text-muted-foreground">Campus Nexus admin</p><h1 className="font-display text-xl font-bold">{title}</h1></div></div><div className="flex items-center gap-2"><button className="grid h-10 w-10 place-items-center rounded-xl border border-border bg-card text-muted-foreground" aria-label="Notifications" data-testid="button-admin-notifications"><Bell size={17} /></button><span className="grid h-10 w-10 place-items-center rounded-full bg-accent text-xs font-bold text-accent-foreground">AR</span></div></header><main className="mx-auto max-w-[1500px] p-4 sm:p-8">{children}</main></div></div>;
}

export function StatCard({ icon: Icon, label, value, note, tone = 'teal' }: { icon: typeof Users; label: string; value: string; note: string; tone?: 'teal'|'gold'|'lavender' }) {
  return <div className="rounded-2xl border border-border bg-card p-5 shadow-sm"><div className="flex items-start justify-between"><span className={cx('grid h-10 w-10 place-items-center rounded-xl', tone === 'teal' && 'bg-primary/10 text-primary', tone === 'gold' && 'bg-accent/20 text-[#8b5e13] dark:text-accent', tone === 'lavender' && 'bg-[#7f77a8]/15 text-[#655c8b] dark:text-[#bbb5e5]')}><Icon size={19} /></span><span className="text-xs font-bold text-primary">+{Math.floor(Math.random()*7)+2}%</span></div><p className="mt-5 text-sm font-semibold text-muted-foreground">{label}</p><p className="mt-1 font-display text-3xl font-bold">{value}</p><p className="mt-1 text-xs text-muted-foreground">{note}</p></div>;
}

export function Leaderboard({ pointsHidden, setPointsHidden }: { pointsHidden: boolean; setPointsHidden: (v: boolean) => void }) {
  const sorted = [...seedResults].sort((a,b) => b.totalPoints - a.totalPoints).slice(0,5);
  return <section className="rounded-2xl border border-border bg-card p-5 shadow-sm sm:p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="flex items-center gap-2"><span className="live-dot h-2 w-2 rounded-full bg-[#e9b84c]" /><span className="text-xs font-bold uppercase tracking-[.15em] text-primary">Live board</span></div><h2 className="mt-1 font-display text-2xl font-bold">Live top 5 projects</h2></div><label className="flex cursor-pointer items-center gap-2 text-xs font-semibold text-muted-foreground"><input type="checkbox" checked={pointsHidden} onChange={e => setPointsHidden(e.target.checked)} className="h-4 w-4 accent-[#176866]" data-testid="toggle-hide-points" /> Hide points on display</label></div><div className="mt-5 space-y-3">{sorted.map((r,i) => { const p = seedProjects.find(x => x.id === r.projectId)!; return <div key={r.projectId} className="flex items-center gap-3 rounded-xl bg-muted/60 p-3"><span className={cx('grid h-8 w-8 shrink-0 place-items-center rounded-lg font-display text-lg font-bold', i === 0 ? 'bg-accent text-[#25334d]' : 'bg-card text-muted-foreground')}>{i+1}</span><img src={p.imageUrl} alt="" className="h-10 w-12 shrink-0 rounded-lg object-cover" /><div className="min-w-0 flex-1"><div className="flex justify-between gap-3"><p className="truncate text-sm font-bold">{p.title}</p><strong className="shrink-0 text-sm text-primary">{pointsHidden ? '•••' : `${r.totalPoints} pts`}</strong></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-border"><div className="h-full rounded-full bg-primary" style={{ width: `${(r.totalPoints / sorted[0].totalPoints) * 100}%` }} /></div></div></div>; })}</div></section>;
}

export function PageIntro({ eyebrow, title, action }: { eyebrow: string; title: string; action?: ReactNode }) { return <div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.17em] text-primary">{eyebrow}</p><h2 className="mt-1 font-display text-3xl font-bold">{title}</h2></div>{action}</div>; }

export function Field({ label, value, onChange, placeholder, error, textarea, select, wide, max }: { label: string; value: string; onChange: (v: string) => void; placeholder?: string; error?: boolean; textarea?: boolean; select?: boolean; wide?: boolean; max?: number }) { return <label className={cx('block', wide && 'sm:col-span-2')}><span className="mb-1.5 block text-sm font-bold">{label}</span>{select ? <select value={value} onChange={e => onChange(e.target.value)} className={cx('w-full rounded-xl border bg-background px-3 py-3 text-sm', error ? 'border-destructive' : 'border-border')}>{projectMajors.slice(1).map(([, major]) => <option key={major}>{major}</option>)}</select> : textarea ? <textarea value={value} onChange={e => onChange(e.target.value)} maxLength={max} rows={4} placeholder={placeholder} className={cx('w-full resize-y rounded-xl border bg-background px-3 py-3 text-sm', error ? 'border-destructive' : 'border-border')} /> : <input value={value} onChange={e => onChange(e.target.value)} placeholder={placeholder} className={cx('w-full rounded-xl border bg-background px-3 py-3 text-sm', error ? 'border-destructive' : 'border-border')} />}{max && <span className="mt-1 block text-right text-[11px] text-muted-foreground">{value.length}/{max}</span>}</label>; }

export function SettingsCard({ icon, title, children }: { icon: ReactNode; title: string; children: ReactNode }) { return <section className="rounded-2xl border border-border bg-card p-5 shadow-sm sm:p-7"><div className="flex items-center gap-3 border-b border-border pb-4"><span className="grid h-10 w-10 place-items-center rounded-xl bg-primary/10 text-primary">{icon}</span><h2 className="font-display text-2xl font-bold">{title}</h2></div><div className="pt-5">{children}</div></section>; }
export function Toggle({ label, checked, onChange }: { label: string; checked: boolean; onChange: () => void }) { return <label className="flex cursor-pointer items-center justify-between border-b border-border py-3 text-sm font-semibold last:border-0"><span>{label}</span><button role="switch" aria-checked={checked} onClick={onChange} className={cx('relative h-7 w-12 rounded-full transition', checked ? 'bg-primary' : 'bg-muted')} data-testid={`toggle-${label.toLowerCase().replace(/\s+/g,'-')}`}><span className={cx('absolute top-1 h-5 w-5 rounded-full bg-white shadow-sm transition', checked ? 'left-6' : 'left-1')} /></button></label>; }
