'use client';

import { useState } from 'react';
import { useParams, useRouter } from 'next/navigation';
import { ImagePlus } from 'lucide-react';
import { projects as seedProjects } from '../../data/data';
import { mockServices } from '../../data/services';
import type { Project } from '../../data/types';
import { Button, Toast, useToastMessage } from '../../components/ui';
import { AdminShell, Field, PageIntro } from '../../components/admin';

export function ProjectForm({ existing }: { existing?: Project }) {
  const router = useRouter(); const [form, setForm] = useState({ number: existing?.projectNumber || '', title: existing?.title || '', short: existing?.shortDescription || '', full: existing?.fullDescription || '', team: existing?.teamName || '', category: existing?.category || 'Information Science and Technology', image: existing?.imageUrl || '' }); const [errors, setErrors] = useState<string[]>([]); const { notify, message, clear } = useToastMessage();
  const update = (key: string, value: string) => setForm(f => ({ ...f, [key]: value }));
  const submit = async (publish: boolean) => { const next = Object.entries(form).filter(([k,v]) => ['number','title','short','full','team'].includes(k) && !v.trim()).map(([k]) => k); if (next.length) { setErrors(next); return; } setErrors([]); existing ? await mockServices.updateProject(existing.id, {}) : await mockServices.createProject({ projectNumber: form.number, title: form.title, shortDescription: form.short, fullDescription: form.full, teamName: form.team, category: form.category, imageUrl: form.image || seedProjects[0].imageUrl, isActive: publish, isArchived: false, features: [] }); notify(publish ? 'Project published in the demo' : 'Draft saved locally'); setTimeout(() => router.push('/admin/projects'), 500); };
  return <AdminShell title={existing ? 'Edit project' : 'New project'}><PageIntro eyebrow="Project catalogue" title={existing ? `Edit ${existing.title}` : 'Add a project'} /><div className="grid gap-5 lg:grid-cols-[1fr_360px]"><div className="rounded-2xl border border-border bg-card p-5 shadow-sm sm:p-7"><div className="grid gap-5 sm:grid-cols-2"><Field label="Project number" value={form.number} error={errors.includes('number')} onChange={v => update('number',v)} placeholder="13" /><Field label="Team name" value={form.team} error={errors.includes('team')} onChange={v => update('team',v)} placeholder="The Makers" /><Field label="Project title" value={form.title} error={errors.includes('title')} onChange={v => update('title',v)} placeholder="A memorable title" wide /><Field label="Category" value={form.category} onChange={v => update('category',v)} select wide /><Field label="Short description" value={form.short} error={errors.includes('short')} onChange={v => update('short',v)} textarea wide max={180} /><Field label="Full description" value={form.full} error={errors.includes('full')} onChange={v => update('full',v)} textarea wide max={600} /></div><div className="mt-6 flex flex-wrap justify-end gap-2 border-t border-border pt-5"><Button variant="quiet" onClick={() => router.push('/admin/projects')}>Cancel</Button><Button variant="outline" onClick={() => submit(false)}>Save draft</Button><Button onClick={() => submit(true)}>Publish project</Button></div></div><div className="rounded-2xl border border-border bg-card p-5 shadow-sm"><p className="text-sm font-bold">Project image</p><div className="mt-3 overflow-hidden rounded-xl border-2 border-dashed border-border bg-muted">{form.image ? <img src={form.image} alt="Project preview" className="aspect-[1.5] w-full object-cover" /> : <div className="grid aspect-[1.5] place-items-center text-center text-sm text-muted-foreground"><ImagePlus className="mx-auto mb-2 text-primary" />Drop an image here<br />or browse files</div>}</div><p className="mt-3 text-xs leading-5 text-muted-foreground">JPG, PNG or WEBP · Recommended 1200 × 800 px. Mock upload preview only.</p><Button variant="outline" className="mt-4 w-full" onClick={() => update('image', seedProjects[Math.floor(Math.random()*seedProjects.length)].imageUrl)}><ImagePlus size={16} /> Use demo image</Button></div></div>{errors.length > 0 && <p className="mt-4 rounded-xl bg-destructive/10 p-3 text-sm font-semibold text-destructive" role="alert">Please complete the highlighted required fields.</p>}{message && <Toast message={message} onClose={clear} />}</AdminShell>;
}

export function EditProjectPage() {
  const { id } = useParams<{ id: string }>();
  return <ProjectForm existing={seedProjects.find(project => project.id === id)} />;
}
