'use client';

import { useRouter } from 'next/navigation';
import { ChevronDown, CircleHelp, Heart, ShieldCheck, Sparkles } from 'lucide-react';
import { mockServices } from '../../data/services';
import { Badge, Button, Toast, VoterHeader, useToastMessage } from '../../components/ui';

export function HomePage() {
  const router = useRouter(); const { notify, message, clear } = useToastMessage();
  const login = async () => { await mockServices.loginWithGoogle(); notify('Demo account ready'); setTimeout(() => router.push('/choose-category'), 300); };
  return <main className="page-shell paper-grain overflow-hidden"><VoterHeader /><div className="mx-auto grid max-w-6xl gap-10 px-4 pb-16 pt-7 sm:px-6 lg:grid-cols-[1.05fr_.95fr] lg:items-center lg:gap-20 lg:pt-14">
    <section className="animate-in"><Badge tone="gold">Innovation Expo 2026 · voting online</Badge><h1 className="glow-text mt-5 max-w-xl font-display text-[clamp(3rem,11vw,6.7rem)] font-bold leading-[.92] tracking-[-.04em]">Every idea<br /><em className="text-primary">shapes</em><br />the future.</h1><p className="mt-7 max-w-md text-base leading-7 text-muted-foreground">Enter the university’s shared grid of bold research, emerging technology and student-built experiments.</p><div className="mt-8 max-w-md"><Button onClick={login} className="w-full sm:w-auto">Enter voting portal <ChevronDown size={16} className="-rotate-90" /></Button><p className="mt-4 flex items-center gap-2 text-xs text-muted-foreground"><ShieldCheck size={14} className="text-primary" />Demonstration access · one locally recorded vote.</p></div></section>
    <section className="relative animate-in delay-2"><div className="absolute -right-16 -top-14 h-48 w-48 rounded-full bg-primary/20 blur-3xl" /><div className="glow-border relative overflow-hidden rounded-[2rem] bg-[#101d2c] p-5"><div className="flex items-center justify-between text-xs font-bold uppercase tracking-[.18em] text-primary"><span>Gallery note 01</span><span>Look closer</span></div><div className="relative mt-5 flex aspect-[.94] items-center justify-center overflow-hidden rounded-[1.35rem] bg-[#172d3c]"><div className="absolute h-56 w-56 rounded-full border-[18px] border-accent opacity-90" /><div className="absolute h-36 w-36 rounded-full border-[12px] border-[#8f86ff]" /><div className="absolute h-5 w-52 rotate-45 bg-primary" /><div className="absolute h-5 w-52 -rotate-45 bg-primary" /><div className="relative grid h-24 w-24 place-items-center rounded-full bg-[#0b121e] text-primary shadow-[0_0_30px_hsl(188_100%_62%/.3)]"><Sparkles size={40} /></div><span className="absolute bottom-6 left-6 max-w-[170px] font-display text-2xl font-bold leading-tight text-foreground">Made by<br />many hands.</span></div><div className="flex items-end justify-between pt-5 text-foreground"><p className="max-w-[210px] text-sm leading-5 text-muted-foreground">12 projects. 36 voices. One campus, building tomorrow.</p><span className="font-display text-5xl font-bold text-accent">25</span></div></div></section>
  </div><section className="mx-auto flex max-w-6xl flex-wrap gap-x-10 gap-y-3 border-t border-border px-4 py-8 text-xs font-semibold text-muted-foreground sm:px-6"><span className="flex items-center gap-2"><ShieldCheck size={15} className="text-primary" />Clear, fair voting</span><span className="flex items-center gap-2"><Heart size={15} className="text-primary" />Built by our community</span><span className="flex items-center gap-2"><CircleHelp size={15} className="text-primary" />Need help? Ask a host</span></section>{message && <Toast message={message} onClose={clear} />}</main>;
}

